### ISSUE TITLE
Convert project to TypeScript

### ISSUE THREAD

**Issue by thekidnamedkd** [mmsaki/PA-Mint-House#1]
https://nextjs.org/learn/excel/typescript
https://www.typescriptlang.org/docs/handbook/migrating-from-javascript.html
https://www.geeksforgeeks.org/how-to-add-typescript-in-next-js/

**Comment by mmsaki** [comment]
Done! Typescript integration should be good to go!

**Comment by mmsaki** [comment]
Closing this issue since it's been resolved!
